# Generated by Django 5.2 on 2025-07-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mollavie_shop', '0007_alter_order_options_order_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='orders',
                to='auth.user',
            ),
        ),
    ]
