# Generated by Django 5.2 on 2025-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollavie_shop', '0009_alter_order_customer'),
    ]

    operations = [
         migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(
                to='auth.user',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                related_name='orders'
            ),
        ),
    ]