# mollavie_shop/admin.py

from django.contrib import admin
from .models import Category, Product, CustomerProfile, Order, OrderItem
from .models import NewsletterSubscriber


@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    list_display = ("name", "price", "is_available", "created_at")
    list_editable = ("is_available",)
    list_filter = ("is_available",)
    search_fields = ("name",)
    ordering = ("-created_at",)


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    prepopulated_fields = {"slug": ("name",)}


admin.site.register(CustomerProfile)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(NewsletterSubscriber)










# Generated by Django 5.2 on 2025-07-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mollavie_shop', '0009_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(
                to='auth.user',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='orders',
            ),
        ),
    ]